// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2wkTjPq1AZWs-bxicP6mbSb2n4guuqzA',
    appId: '1:960734061943:android:55ab23ac33d50e3d54ad72',
    messagingSenderId: '960734061943',
    projectId: 'coinverse-7bf00',
    storageBucket: 'coinverse-7bf00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcq9_i4IYZ4UwtOGO_mH-LJUtL0Q6mUtY',
    appId: '1:960734061943:ios:317ac6cf2a68ba0a54ad72',
    messagingSenderId: '960734061943',
    projectId: 'coinverse-7bf00',
    storageBucket: 'coinverse-7bf00.appspot.com',
    androidClientId: '960734061943-9085nte5eg93gujhs9l6fpegole42rhb.apps.googleusercontent.com',
    iosClientId: '960734061943-de9bppq959du0tsuei7bi1ki2e7rkdks.apps.googleusercontent.com',
    iosBundleId: 'com.example.coinverse',
  );
}
